[package]
name = "lsl-sys"
version = "0.1.1"
authors = ["Intheon <contact@intheon.io>", "Christian Kothe <christian.kothe@intheon.io>"]
edition = "2018"
description = "Low-level bindings to the system liblsl library (lab streaming layer)."
repository = "https://github.com/labstreaminglayer/liblsl-rust"
license = "MIT"
keywords = ["lsl", "ffi"]
categories = ["external-ffi-bindings"]
links = "lsl"

[features]
system = ["dep:pkg-config", "dep:vcpkg"]
bundled = ["dep:cmake"]
bindgen = ["dep:bindgen"]
default = ["system", "bundled", "bindgen"]

[build-dependencies]
cmake = { version = "0.1.44", optional = true }
bindgen = { version = "0.72", optional = true }
pkg-config = { version = "0.3", optional = true }

[target.'cfg(windows)'.build-dependencies]
vcpkg = { version = "0.2", optional = true }
